var searchData=
[
  ['sam_20advanced_20encryption_20standard_20_28aes_29_20driver',['SAM Advanced Encryption Standard (AES) Driver',['../group__asfdoc__sam0__drivers__aes__group.html',1,'']]],
  ['sam_20port_20_28port_29_20driver',['SAM Port (PORT) Driver',['../group__asfdoc__sam0__port__group.html',1,'']]],
  ['sam_20serial_20usart_20_28sercom_20usart_29_20driver',['SAM Serial USART (SERCOM USART) Driver',['../group__asfdoc__sam0__sercom__usart__group.html',1,'']]],
  ['sam_20system_20clock_20management_20_28system_20clock_29_20driver',['SAM System Clock Management (SYSTEM CLOCK) Driver',['../group__asfdoc__sam0__system__clock__group.html',1,'']]],
  ['sam_20system_20_28system_29_20driver',['SAM System (SYSTEM) Driver',['../group__asfdoc__sam0__system__group.html',1,'']]],
  ['sam_20system_20interrupt_20_28system_20interrupt_29_20driver',['SAM System Interrupt (SYSTEM INTERRUPT) Driver',['../group__asfdoc__sam0__system__interrupt__group.html',1,'']]],
  ['sam_20system_20pin_20multiplexer_20_28system_20pinmux_29_20driver',['SAM System Pin Multiplexer (SYSTEM PINMUX) Driver',['../group__asfdoc__sam0__system__pinmux__group.html',1,'']]],
  ['status_20and_20control_20registers',['Status and Control Registers',['../group___c_m_s_i_s___c_o_r_e.html',1,'']]],
  ['systick_20functions',['SysTick Functions',['../group___c_m_s_i_s___core___sys_tick_functions.html',1,'']]],
  ['system_20control_20block_20_28scb_29',['System Control Block (SCB)',['../group___c_m_s_i_s___s_c_b.html',1,'']]],
  ['system_20tick_20timer_20_28systick_29',['System Tick Timer (SysTick)',['../group___c_m_s_i_s___sys_tick.html',1,'']]],
  ['standard_20i_2fo_20_28stdio_29',['Standard I/O (stdio)',['../group__group__common__utils__stdio.html',1,'']]],
  ['standard_20serial_20i_2fo_20_28stdio_29',['Standard serial I/O (stdio)',['../group__group__common__utils__stdio__stdio__serial.html',1,'']]],
  ['status_20codes',['Status Codes',['../group__group__sam0__utils__status__codes.html',1,'']]],
  ['statistics_20functions',['Statistics Functions',['../group__group_stats.html',1,'']]],
  ['support_20functions',['Support Functions',['../group__group_support.html',1,'']]],
  ['sam_20parts',['SAM parts',['../group__sam__part__macros__group.html',1,'']]],
  ['saml21_20device_20definitions',['SAML21 Device Definitions',['../group___s_a_m_l21__definitions.html',1,'']]],
  ['serial_20communication_20interface',['Serial Communication Interface',['../group___s_a_m_l21___s_e_r_c_o_m.html',1,'']]],
  ['supply_20controller',['Supply Controller',['../group___s_a_m_l21___s_u_p_c.html',1,'']]],
  ['sam_20l21_20xplained_20pro_20board',['SAM L21 Xplained Pro board',['../group__saml21__xplained__pro__group.html',1,'']]],
  ['saml21e18a_20definitions',['SAML21E18A definitions',['../group___s_a_m_l21_e18_a__definitions.html',1,'']]],
  ['saml21g18a_20definitions',['SAML21G18A definitions',['../group___s_a_m_l21_g18_a__definitions.html',1,'']]],
  ['saml21j18a_20definitions',['SAML21J18A definitions',['../group___s_a_m_l21_j18_a__definitions.html',1,'']]],
  ['serial_20interface_20_28serial_29',['Serial Interface (Serial)',['../group__serial__group.html',1,'']]],
  ['square_20root',['Square Root',['../group___s_q_r_t.html',1,'']]]
];
